# Generated by Django 4.1.3 on 2022-11-22 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newspaper", "0002_alter_redactor_years_of_experience"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newspaper",
            options={"ordering": ["published_date"]},
        ),
        migrations.AlterModelOptions(
            name="redactor",
            options={
                "ordering": ["years_of_experience"],
                "verbose_name": "redactor",
                "verbose_name_plural": "redactors",
            },
        ),
    ]
