# Generated by Django 4.1.3 on 2022-11-22 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newspaper", "0003_alter_newspaper_options_alter_redactor_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newspaper",
            options={"ordering": ["-published_date"]},
        ),
        migrations.AlterModelOptions(
            name="redactor",
            options={
                "ordering": ["-years_of_experience"],
                "verbose_name": "redactor",
                "verbose_name_plural": "redactors",
            },
        ),
    ]
